apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: payment-pipeline
spec:
  resources:
    - name: source
      type: git
  tasks:
    - name: build
      taskRef:
        name: build-docker-image-from-git-source-payment
      resources:
        inputs: 
        - name: payment
          resource: source
    - name: payment-deploy-using-kubectl
      runAfter: ["build"]
      taskRef:
        name: payment-deploy-using-kubectl
      resources:
        inputs:
        - name: payment
          resource: source
