apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: runner
spec:
  serviceAccountName: build-bot
  taskRef:
    name: build-docker-image-from-git-source-edge-router
  params:
  - name: IMAGE
    value: "saloyiana/edge-router"
  resources:
    inputs:
    - name: docker-source
      resourceRef:
        name: edge-router
