apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: orders
spec:
  type: git
  params:
    - name: revision
      value: develop
    - name: url
      value: https://github.com/saloyiana/finalProject
