apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: orders-run
spec:
  serviceAccountName: build-bot
  taskRef:
    name: build-docker-image-from-git-source-orders
  params:
  - name: IMAGE
    value: "saloyiana/orders"
  resources:
    inputs:
    - name: docker-source
      resourceRef:
        name: orders
