apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: carts
spec:
  resources:
    - name: source
      type: git
  tasks:
    - name: build
      taskRef:
        name: build-docker-image-from-git-source-carts
      resources:
        inputs: 
        - name: carts
          resource: source
    - name: deploy-using-kubectl
      runAfter: ["build"]
      taskRef:
        name: carts-deploy-using-kubectl
      resources:
        inputs:
        - name: carts
          resource: source
