apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: carts-run
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: carts 
  resources:
    - name: source
      resourceRef:
        name: carts
