apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: user-run
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: user-pipeline 
  resources:
    - name: source
      resourceRef:
        name: user
