apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: user-pipeline
spec:
  resources:
    - name: source
      type: git
  tasks:
    - name: build
      taskRef:
        name: build-docker-image-from-git-source-front-end
      resources:
        inputs: 
        - name: user
          resource: source
    - name: deploy-using-kubectl
      runAfter: ["build"]
      taskRef:
        name: deploy-using-kubectl
      resources:
        inputs:
        - name: user
          resource: source
