apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: frontend
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: front-end
          servicePort: 8079
