apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: catalogue-db
spec:
  serviceAccountName: build-bot
  taskRef:
    name: build-docker-image-from-git-source-catalogue-db
  params:
  - name: IMAGE
    value: "saloyiana/catalogue-db"
  resources:
    inputs:
    - name: docker-source
      resourceRef:
        name: catalogue
