apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user
  template:
    metadata:
      labels:
        name: user
    spec:
      containers:
      - name: user
        image: saloyiana/user
        ports:
        - containerPort: 80
        env:
        - name: mongo
          value: user-db:27017
      nodeSelector:
        beta.kubernetes.io/os: linux
