apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: user-pipeline
spec:
  resources:
    - name: source
      type: git
  tasks:
    - name: build
      taskRef:
        name: build-docker-image-from-git-source-user
      resources:
        inputs: 
        - name: user
          resource: source
    - name: deploy-using-kubectl
      runAfter: ["build"]
      taskRef:
        name: user-deploy-using-kubectl
      resources:
        inputs:
        - name: user
          resource: source
    - name: run-test
      runAfter: ["deploy-using-kubectl"]
      taskRef:
        name: test-deploy-user
      resources:
        inputs:
        - name: user
          resource: source
    - name: deploy-to-prod
      runAfter: ["run-test"]
      taskRef:
        name: user-deploy-using-kubectl-prod
      resources:
        inputs:
        - name: user 
          resource: source 
