apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: orders-pipeline
spec:
  resources:
    - name: source
      type: git
  tasks:
    - name: build
      taskRef:
        name: build-docker-image-from-git-source-orders
      resources:
        inputs: 
        - name: orders-resource
          resource: source
    - name: orders-deploy-using-kubectl
      runAfter: ["build"]
      taskRef:
        name: orders-deploy-using-kubectl
      resources:
        inputs:
        - name: orders-resource
          resource: source
