apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: frontend-runner
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: frontend-pipeline 
  resources:
    - name: source
      resourceRef:
        name: frontend-resource
