apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: frontend-pipeline
spec:
  resources:
    - name: source
      type: git
  tasks:
    - name: build
      taskRef:
        name: build-docker-image-from-git-source-front-end
      resources:
        inputs: 
        - name: frontend-resource
          resource: source
    - name: frontend-deploy-using-kubectl
      runAfter: ["build"]
      taskRef:
        name: frontend-deploy-using-kubectl
      resources:
        inputs:
        - name: frontend-resource
          resource: source
    - name: run-test
      runAfter: ["frontend-deploy-using-kubectl"]
      taskRef:
        name: test-deploy
      resources:
        inputs:
        - name: frontend-resource
          resource: source
    - name: deploy-to-prod
      runAfter: ["run-test"]
      taskRef:
        name: frontend-deploy-using-kubectl
      resources:
        inputs:
        - name: frontend-resource 
          resource: source 
