apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-deploy
  serviceAccountName: build-bot
spec:
  params:
    - name: pathToYamlFile
      type: string
      description: The path to the yaml file to deploy within the git source
      default: $(resources.inputs.frontend-resource.path)/cicd/frontend/k8s/test.yaml
  resources:
    inputs:
      - name: frontend-resource
        type: git
  steps:
   - name: run-kubectl
     image: lachlanevenson/k8s-kubectl
     command: ["kubectl"]
     args:
       - "apply"
       - "-f"
       - "$(params.pathToYamlFile)"
       - "-n"
       - "test"
   - name: run-wait
    image: lachlanevenson/k8s-kubectl
    script: |
     kubectl wait --for=condition=complete job/test -n test
