apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-deploy
  serviceAccountName: build-bot
spec:
  params:
    - name: pathToSh
      type: string
      description: The path to the yaml file to deploy within the git source
      default: $(resources.inputs.frontend-resource.path)/test/e2e-js-test/runner.sh
  resources:
    inputs:
      - name: frontend-resource
        type: git
  steps:
   - name: debug
     workingDir: /workspace/frontend-resource/test/e2e-js-test/
     image: ubuntu
     script: | 
       #!/usr/bin/env bash
       pwd 
       ls -gAhF
   - name: run-test
     workingDir: /workspace/frontend-resource/test/e2e-js-test/
     image: node:alpine
     script: |
       #!/usr/bin/env sh
       apk add --update --no-cache make git curl jq python3 && ln -sf python3 /usr/bin/python
       python3 -m ensurepip
       pip3 install --no-cache --upgrade pip setuptools
       npm install -g casperjs mocha jscodeshift
       cd /tmp
       curl -Ls https://github.com/dustinblackman/phantomized/releases/download/2.1.1/dockerized-phantomjs.tar.gz | tar xz && cp -R lib lib64 && cp -R usr/lib/x86_64-linux-gnu /usr/lib && curl -k -Ls https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar -jxf - && cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs &&  rm -rf /tmp/*
       chmod +x runner.sh
       sh runner.sh

