apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: frontend-deploy-using-kubectl
  serviceAccountName: build-bot
spec:
  params:
    - name: pathToYamlFile
      type: string
      description: The path to the yaml file to deploy within the git source
      default: $(resources.inputs.frontend-resource.path)/cicd/frontend/k8s/deploy.yaml
  resources:
    inputs:
      - name: frontend-resource
        type: git
  steps:
   - name: run-kubectl
     image: lachlanevenson/k8s-kubectl
     command: ["kubectl"]
     args:
       - "apply"
       - "-f"
       - "$(params.pathToYamlFile)"
       - "-f"
       - "$(resources.inputs.frontend-resource.path)/cicd/frontend/k8s/svc.yaml"
       - "-f"
       - "$(resources.inputs.frontend-resource.path)/cicd/frontend/k8s/ingress.yaml"
       - "-f"
       - "$(resources.inputs.frontend-resource.path)/cicd/frontend/k8s/rabbitmq.yaml"
    - name: run-test
      image: bryandollery/terraform-packer-aws-alpine
      script: | 
        #!bin/bash 
        ip="$(curl http://checkip.amazonaws.com)"
        echo $ip

        cat << EOF | kubectl apply -f -
        ---
        apiVersion: batch/v1
        kind: Job
        metadata:
        name: e2e-js-test
        spec:
        parallelism: 1
        completions: 1
        backoffLimit: 3
        activeDeadlineSeconds: 20
        template:
        metadata:
            labels:
                app: "e2e-js-test"
                run: "1"
                version: "1"
        spec:
            restartPolicy: Never
            containers:
            - name: chrome
              image: saloyiana/e2ejstest
              env:
              - name: "TARGET_URL"
                value: "$ip:30001"
        EOF

