apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-deploy
  serviceAccountName: build-bot
spec:
  params:
    - name: pathToSh
      type: string
      description: The path to the yaml file to deploy within the git source
      default: $(resources.inputs.frontend-resource.path)/test/e2e-js-test/runner.sh
  resources:
    inputs:
      - name: frontend-resource
        type: git
  steps:
   - name: debug
     workingDir: /workspace/frontend-resource/test/e2e-js-test/
     image: ubuntu
      script: | 
        #!/usr/bin/env bash
        pwd 
        ls -gAhF
   - name: run-test
     image: ubuntu
     command: 
     - chmod +x "$(params.pathToSh)"
     - sh "$(params.pathToSh)"
