apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: frontend-resource
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/microservices-demo/front-end
