apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: deployrunner
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: frontend-pipeline 
  resources:
    - name: source
      resourceRef:
        name: docker-source
