apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: catalogue
spec:
  resources:
    - name: source
      type: git
  tasks:
    - name: build
      taskRef:
        name: build-docker-image-from-git-source-catalogue
      resources:
        inputs: 
        - name: catalogue
          resource: source
    - name: deploy-using-kubectl
      runAfter: ["build"]
      taskRef:
        name: catalogue-deploy-using-kubectl
      resources:
        inputs:
        - name: catalogue
          resource: source
