apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: shipping-pipeline
spec:
  resources:
    - name: source
      type: git
  tasks:
    - name: build
      taskRef:
        name: build-docker-image-from-git-source-shipping
      resources:
        inputs: 
        - name: shipping
          resource: source
    - name: shipping-deploy-using-kubectl
      runAfter: ["build"]
      taskRef:
        name: shipping-deploy-using-kubectl
      resources:
        inputs:
        - name: shipping
          resource: source
    - name: run-test
      runAfter: ["deploy-using-kubectl"]
      taskRef:
        name: test-deploy-shipping
      resources:
        inputs:
        - name: shipping
          resource: source
    - name: deploy-to-prod
      runAfter: ["run-test"]
      taskRef:
        name: shipping-deploy-using-kubectl-prod
      resources:
        inputs:
        - name: shipping 
          resource: source 
