apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: payment-deploy-using-kubectl
  serviceAccountName: build-bot
spec:
  params:
    - name: pathToYamlFile
      type: string
      description: The path to the yaml file to deploy within the git source
      default: $(resources.inputs.payment.path)/cicd/payment/k8s/deploy.yaml
  resources:
    inputs:
      - name: payment
        type: git
  steps:
   - name: run-kubectl
     image: lachlanevenson/k8s-kubectl
     command: ["kubectl"]
     args:
       - "apply"
       - "-f"
       - "$(params.pathToYamlFile)"
       - "-f"
       - "$(resources.inputs.payment.path)/cicd/payment/k8s/svc.yaml"
