apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: payment
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/microservices-demo/payment
