apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: shipping-run
spec:
  serviceAccountName: build-bot
  taskRef:
    name: build-docker-image-from-git-source-shipping
  params:
  - name: IMAGE
    value: "saloyiana/shipping"
  resources:
    inputs:
    - name: docker-source
      resourceRef:
        name: shipping
