apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    name: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalogue
  template:
    metadata:
      labels:
        name: catalogue
    spec:
      containers:
      - name: catalogue
        image: saloyiana/catalogue
        ports:
        - containerPort: 80
        securityContext:
          privileged: true
      nodeSelector:
        beta.kubernetes.io/os: linux
