apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: runner
spec:
  serviceAccountName: build-bot
  taskRef:
    name: build-docker-image-from-git-source-e2e
  params:
  - name: IMAGE
    value: "saloyiana/e2e-test"
  resources:
    inputs:
    - name: docker-source
      resourceRef:
        name: e2e
